### ISSUE TITLE
Problem created in the new version of bidi with Beamer class! 

### ISSUE THREAD

**Issue by mojtabaahmadi2020tl** [tex-persian/bidi#2]
% !TeX TS-program = xelatex
\documentclass[10pt]{beamer}
\usetheme{Warsaw}

\usepackage[RTLdocument]{bidi} 
\title{Warsaw and bidi}
\author{M.Ahmadi}
\begin{document}

\section{section}
\begin{frame}{title}
test
\end{frame}

\end{document}

درود جناب وفا،
 در نسخه 36.4 bidi تست شده  و مشکل در کادر عنوان فریم هستش.
با تشکر از زحمات

[tset-bem13.pdf](https://github.com/tex-persian/bidi/files/7992862/tset-bem13.pdf)

**Comment by vafa-khalighi** [comment]
Thanks for your bug report. Can you confirm whether the issue exists with the previous version of the `bidi` package or that version 36.4 introduced it?

**Comment by mojtabaahmadi2020tl** [comment]
درود جناب وفا، در نسخه قبلی bidi مشکلی نداشت. با تشکر از زحمات

**Comment by vafa-khalighi** [comment]
I have uploaded version 36.6 2022-02-13 of the `bidi` package to CTAN which should fix this issue. Please test the new version against this issue and if it fixes it, then please close this issue. Otherwise, please let me know what needs to be done so that I can fix it.
