### ISSUE TITLE
Problem created in the new version of bidi with tikz!

### ISSUE THREAD

**Issue by mojtabaahmadi2020tl** [tex-persian/bidi#3]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/tex-persian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/tex-persian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode

\documentclass{article}
\usepackage{tikz} 
\usepackage[RTLdocument]{bidi} 

\begin{document}
test
\begin{tikzpicture}[rounded corners,ultra thick]
\shade[ball color=green] (0,0) circle (1cm);
\end{tikzpicture}
\end{document}
```

## Log and PDF files  

[tikz_bidi.log](https://github.com/tex-persian/bidi/files/8049210/tikz_bidi.log)
[tikz_bidi.pdf](https://github.com/tex-persian/bidi/files/8049211/tikz_bidi.pdf)

**Comment by vafa-khalighi** [comment]
I have uploaded version 36.6 2022-02-13 of the `bidi` package to CTAN which should fix this issue. Please test the new version against this issue and if it fixes it, then please close this issue. Otherwise, please let me know what needs to be done so that I can fix it.
