### ISSUE TITLE
The problem of formula parentheses in bidi 

### ISSUE THREAD

**Issue by mojtabaahmadi2020tl** [tex-persian/bidi#7]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/tex-persian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/tex-persian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode

\documentclass{article}

\usepackage{amsmath} 
\usepackage{fontspec}
\setmainfont[Script=Arabic]{Yas} % error --> Script=Persian

\usepackage[RTLdocument]{bidi}

\begin{document}
این فقط یک آزمایش است.
\begin{equation}
\sum_{i=1}^n i=?
\end{equation}
تست
\begin{align}
ax+by&=p\\
cx+dy&=q
\end{align}

\end{document}
```

## Log and PDF files  

[exam_RTL_bidi.pdf](https://github.com/tex-persian/bidi/files/8066993/exam_RTL_bidi.pdf)
[exam_RTL_bidi.log](https://github.com/tex-persian/bidi/files/8066994/exam_RTL_bidi.log)

**Comment by vafa-khalighi** [comment]
This does not happen in `xepersian` because `xepersian` does the right thing in each mode (right to left and left to right). In order to get this right in your minimal example, you need to use the control sequence `\setnonlatin` in the preamble. Therefore, this is considered expected behavior and not a bug.

**Comment by mojtabaahmadi2020tl** [comment]
Thanks
